# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 API Cloud Documentation
site_description: Documentation for WSO2 API Cloud
site_author: WSO2
site_url: https://wso2.com/api-cloud/

# Repository
repo_name: wso2/docs-cloud
repo_url: https://github.com/wso2/docs-cloud
edit_uri: https://github.com/wso2/docs-cloud/edit/master/en/docs/

# Copyright
copyright: WSO2 API Cloud - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'
  
# Navigation
nav:
  - 'Welcome to the WSO2 API Cloud Documentation': index.md
  - 'Get Started':
     - 'Overview': get-started/overview.md
     - 'Key Concepts': get-started/key-concepts.md
     - 'Quick Start Guide': get-started/quick-start-guide.md
  - 'Learn':
     - 'Learn WSO2 API Cloud': learn/learn-wso2-api-cloud.md
     - 'Design & Publish APIs':
        - 'Overview of API Design and Publishing': learn/design-apis/overview-of-api-design-and-publishing.md
        - 'Design an API':
           - 'Design a New REST API': learn/design-apis/design-a-new-rest-api.md
           - 'Design an API Using Existing Swagger Definition': learn/design-apis/design-an-api-using-existing-swagger.md
           - 'Generate a REST API from a SOAP Backend': learn/design-apis/generate-rest-api-from-soap-backend.md
           - 'Expose a SOAP Service as a REST API': learn/design-apis/expose-soap-service-as-rest-api.md
        - 'Publish an API': learn/publish-apis/publish-an-api.md
     - 'Manage APIs':
        - 'Overview of API Lifecycle Management': learn/manage-apis/api-lifecycle-management-overview.md
        - 'Manage API Lifecycle': learn/manage-apis/manage-api-lifecycle.md
        - 'Create a New API Version': learn/manage-apis/create-a-new-api-version.md
        - 'Deprecate an Old API Version': learn/manage-apis/deprecate-an-old-api-version.md
     - 'Backend Integration':
        - 'Overview of Backend Integration': learn/backend-integration/overview-of-backend-integration.md 
        - 'Expose your On-Premises Backend Services to WSO2 API Cloud': learn/backend-integration/expose-your-on-premises-backend-services-to-api-cloud.md
        - 'Use OAuth2 Protected Backends': learn/backend-integration/use-oauth2-protected-backends.md
        - 'Pass a Custom Authorization Token to the Backend': learn/backend-integration/pass-a-custom-authorization-token-to-the-backend.md
        - 'Secure Your Backend Services': learn/backend-integration/secure-your-backend-services.md 
     - 'Message Mediation for APIs':
        - 'Overview of Message Mediation': learn/message-mediation/overview-of-message-mediation.md
        - 'Add a Mediation Sequences to Your API': learn/message-mediation/add-a-sample-mediation-sequence.md
        - 'Add a Custom Sequence to Your API': learn/message-mediation/add-a-custom-sequence-to-your-api.md
     - 'Secure APIs':
        - 'Overview of API Security': learn/secure-apis/api-security-overview.md     
     - 'Consume APIs':
        - 'Overview of Consuming APIs': learn/consume-apis/overview-of-consuming-apis.md
        - 'Discover APIs': learn/consume-apis/discover-apis.md
        - 'Manage Applications':
           - 'Create an Applications': learn/consume-apis/create-applications.md
           - 'Generate Application Keys': learn/consume-apis/generate-application-keys.md
           - 'Share an Application With Your Team': learn/consume-apis/share-an-application-with-your-team.md
        - 'Subscribe to an API': learn/consume-apis/subscribe-to-an-api.md
        - 'Invoke an API':
           - 'Invoke an API Using the Integrated API Console': learn/consume-apis/invoke-an-api.md
           - 'Invoke an API Using CURL': learn/consume-apis/invoke-an-api-using-curl.md
        - 'Generate SDKs':
           - 'Download SDKs for a Published API': learn/consume-apis/download-sdks-for-a-published-api.md
           - 'Write a Client Application Using an SDK': learn/consume-apis/write-a-client-app-using-an-sdk.md
     - 'Control API Traffic':
        - 'Overview of Throttling and Rate Limiting': learn/control-api-traffic/throttling-and-rate-limiting-overview.md
        - 'Apply Throttling Policies':
           - 'Advanced Throttling Policies': learn/control-api-traffic/advanced-throttling-policies.md
           - 'Application Throttling Policies': learn/control-api-traffic/application-throttling-policies.md
           - 'Deny Requests': learn/control-api-traffic/denylist-policies.md
     - 'Analyze APIs':
        - 'Overview of API Analytics': learn/analyze-apis/analytics-overview.md
        - 'View API Statistics': learn/analyze-apis/view-statistics.md
        - 'Work with Alerts': 
           - 'Overview of Working with Alerts': learn/analyze-apis/overview-of-working-with-alerts.md
           - 'Alert Types': learn/analyze-apis/alert-types.md
           - 'Configure Alerts': learn/analyze-apis/configure-alerts.md
           - 'Subscribe to Alerts': learn/analyze-apis/subscribe-to-alerts.md
           - 'View Alerts': learn/analyze-apis/view-alerts.md
     - 'Cloud Administration':
        - 'Overview of Cloud Administration': learn/cloud-administration/overview-of-cloud-administration.md
        - 'Manage Organizations': 
           - 'Overview of Managing Organizations': learn/cloud-administration/overview-of-managing-organizations.md
           - 'Add a New Organization': learn/cloud-administration/add-new-organization.md
           - 'Change the Organization Name': learn/cloud-administration/change-organization-name.md
        - 'Manage Users':
           - 'Overview of Managing Users': learn/cloud-administration/overview-of-managing-users.md
           - 'Add Members to Your Organization': learn/cloud-administration/add-members-to-your-organization.md
           - 'Create Custom Roles': learn/cloud-administration/create-custom-roles.md
           - 'Enable Self Signup to the API Store': learn/cloud-administration/enable-self-sign-up-to-the-api-store.md
           - 'Block Subscription to an API': learn/cloud-administration/block-subscription-to-an-api.md
           - 'Authenticate Users External to WSO2 Cloud': 
              - 'Overview of Authenticating Users External to WSO2 Cloud': learn/cloud-administration/overview-of-authenticating-users-external-to-wso2-cloud.md
              - 'Configure an External Identity Provider for API Cloud Authentication': learn/cloud-administration/configure-an-external-identity-provider-for-api-cloud-authentication.md
              - 'Configure an On-Premises User Store for API Cloud Authentication': learn/cloud-administration/configure-an-on-premises-user-store-for-api-cloud-authentication.md
              - 'Authenticate External Users for API Invocations': learn/cloud-administration/authenticate-external-users-for-api-invocations.md 
        - 'View and Download Logs': learn/cloud-administration/view-and-download-logs.md
        - 'Migrate APIs and Applications Between Environments': learn/cloud-administration/migrate-using-cli-tool.md
     - 'Tutorials':
        - 'Step-by-Step Tutorials': learn/tutorials/step-by-step-tutorials.md
        - 'Create and Publish an API': learn/tutorials/create-and-publish-an-api.md
        - 'Subscribe to and Invoke an API': learn/tutorials/subscribe-to-and-invoke-an-api.md
        - 'Expose Your On-Premises Backend Services to WSO2 API Cloud': learn/tutorials/expose-your-backend-services-to-api-cloud.md
        - 'Enforce Throttling and Resource Access Policies': learn/tutorials/enforce-throttling-and-resource-access-policies.md
        - 'Convert a JSON Message to SOAP and SOAP to JSON': learn/tutorials/convert-a-json-message-to-soap-and-soap-to-json.md
        - 'Change the Default Mediation Flow of API Requests': learn/tutorials/change-default-mediation-flow-of-api-requests.md 
  - 'Customize':
     - 'Customize Your Portal':
        - 'Customize the API Store Theme': customize/customize-the-api-store-theme.md
        - 'Customize Cloud Domains':
           - 'Configure Custom Cloud Domains': customize/customize-cloud-domains.md
           - 'Generate SSL Certificates and DNS Records': customize/generate-ssl-certs-and-dns-records.md
           - 'Customize the API Store Domain': customize/customize-api-store-domain.md
           - 'Customize the API Publisher Domain': customize/customize-api-publisher-domain.md
           - 'Customize the Admin Portal Domain': customize/customize-admin-portal-domain.md
           - 'Customize Gateway Domain': customize/customize-gateway-domain.md
        - 'Customize Invitation Emails': customize/customize-invitation-emails.md
  - 'Hybrid API Management':
     - 'Overview of Hybrid API Management': hybrid-api-management/overview.md
     - 'Deploy the Microgateway': hybrid-api-management/deploy-the-microgateway.md 
     - 'Deploy the Microgateway as a Docker Container': hybrid-api-management/deploy-microgateway-as-docker-container.md
     - 'Deploy the Microgateway on a Kubernetes Cluster': hybrid-api-management/deploy-microgateway-on-kubernetes-cluster.md
     - 'Deploy Grouped APIs Using a Microgateway': hybrid-api-management/deploy-grouped-apis-using-a-microgateway.md
  - 'API Cloud Management APIs':
     - 'Overview of API Cloud Management APIs': management-apis/overview.md
     - 'Common Cloud APIs': management-apis/common-cloud-apis.md
     - 'API Cloud Portal APIs':
        - 'Publisher APIs':
           - 'Get Started with Publisher APIs': management-apis/publisher-get-started.md
           - 'Try Out Publisher APIs': management-apis/publisher-v1.md
        - 'Store APIs':
           - 'Get Started with Store APIs': management-apis/devportal-get-started.md
           - 'Try Out Store APIs': management-apis/devportal-v1.md
        - 'Admin APIs':
           - 'Get Started with Admin APIs': management-apis/admin-get-started.md
           - 'Try Out Admin APIs': management-apis/admin-v1.md
        - 'Analytics APIs':
           - 'Get Started with Analytics APIs': management-apis/analytics-get-started.md
           - 'Try Out Analytics APIs': management-apis/analytics.md
     - 'Subscriber Management APIs': management-apis/subscriber-management-apis.md
     - 'Token API': 
        - 'Overview of Token API': management-apis/token-api.md
        - 'Authorization Code Grant': management-apis/grant-types/authorization-code-grant.md
        - 'Client Credentials Grant': management-apis/grant-types/client-credentials-grant.md
        - 'Password Grant': management-apis/grant-types/password-grant.md
        - 'Refresh Token Grant': management-apis/grant-types/refresh-token-grant.md
        - 'SAML Extension Grant': management-apis/grant-types/saml-extension-grant.md
  - 'Continuous Integration and Deployment': 
     - 'Continuous Integration and Deployment': continuous-integration-and-deployment/continuous-integration-and-deployment-for-wso2-api-cloud.md
  - 'FAQ Library':
     - 'API Creation and Design': faq-library/api-creation-and-design.md
     - 'API Subscription Tiers': faq-library/api-subscription-tiers.md
     - 'API Search': faq-library/api-search.md
     - 'API Deletion': faq-library/api-deletion.md
     - 'API Backend and Endpoint Security': faq-library/api-backends-and-endpoint-security.md
     - 'VPN Connection with API Cloud': faq-library/vpn-with-api-cloud.md
     - 'Request/Response Transformation': faq-library/request-response-transformation.md
     - 'Microgateway': faq-library/microgateway.md
     - 'API Cloud Gateway': faq-library/api-cloud-gateway.md   
  - 'Get Support':
     - 'API Cloud Pricing': get-support/api-cloud-pricing.md
     - 'API Cloud Uptime Status': get-support/uptime-status.md
     - 'Work with the Support Team': get-support/work-with-the-support-team.md
  - '': page-not-found.md 
  

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
    
# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
